# Generated by Django 5.0.4 on 2024-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the film', max_length=128)),
                ('description', models.TextField(help_text='Enter a brief description of the film', max_length=2048)),
                ('publication_date', models.DateField(help_text='Enter the publication date of the film in ISO 8601 format')),
                ('note', models.IntegerField(blank=True, default=0, help_text='Enter the note of the film (optional)', null=True)),
            ],
        ),
    ]
